
export const dataList=[
    {
        tagid:'1',
        name:'新人向け',
        status:false
    },
    {
        tagid:'2',
        name:'製品情報',
        status:false
    },
    {
        tagid:'3',
        name:'office',
        status:false
    },
    {
        tagid:'4',
        name:'システム',
        status:false
    },
    {
        tagid:'5',
        name:'セキュリティ',
        status:false
    },
    {
        tagid:'6',
        name:'新人向け112',
        status:false
    },
    {
        tagid:'7',
        name:'标签一新人向け',
        status:false
    },
    {
        tagid:'8',
        name:'标签新人向け554一的风格',
        status:false
    },
    {
        tagid:'9',
        name:'时代的标sd签新人向け就',
        status:false
    },
    {
        tagid:'10',
        name:'标签电费滚滚十个',
        status:false
    }
]